using Microsoft.UI.Xaml;
using Microsoft.UI.Xaml.Automation;
using Microsoft.UI.Xaml.Automation.Peers;
using Microsoft.UI.Xaml.Automation.Provider;
using Microsoft.UI.Xaml.Controls;
using Microsoft.UI.Xaml.Data;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.VisualStudio.TestTools.UnitTesting.AppContainer;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Threading.Tasks;
using Windows.Foundation.Collections;

namespace WinUI.TableView.Tests;

/// <summary>
/// Covers <see cref="TreeTableView"/> + <see cref="TableViewTreeColumn"/>: the flat-source tree model with
/// source-owned, potentially ASYNCHRONOUS expansion (child count known upfront, children fetched on expand).
/// </summary>
[TestClass]
public class TreeTableViewTests
{
    [UITestMethod]
    public async Task Expand_InsertsChildrenAfterParent_CollapseRemovesThem()
    {
        var (treeTableView, source) = await LoadAsync();
        var root = source[0];

        treeTableView.RequestExpandCollapse(root, 0, expand: true);
        await source.CompletePendingExpandAsync();

        Assert.IsTrue(root.IsExpanded);
        Assert.IsFalse(root.IsLoading);
        Assert.AreEqual(5, treeTableView.Items.Count); // 3 roots + 2 children of root0
        Assert.AreEqual(1, ((TreeNode)treeTableView.Items[1]!).Depth);
        Assert.AreEqual("Root0/Child0", ((TreeNode)treeTableView.Items[1]!).Name);
        Assert.AreEqual("Root1", ((TreeNode)treeTableView.Items[3]!).Name);

        treeTableView.RequestExpandCollapse(root, 0, expand: false);

        Assert.IsFalse(root.IsExpanded);
        Assert.AreEqual(3, treeTableView.Items.Count);

        await UnloadAsync(treeTableView);
    }

    [UITestMethod]
    public async Task AsyncExpand_IsLoadingGate_BlocksReentrantRequests()
    {
        var (treeTableView, source) = await LoadAsync();
        var root = source[0];
        var expandRequests = 0;
        treeTableView.ExpandRequested += (_, _) => expandRequests++;

        treeTableView.RequestExpandCollapse(root, 0, expand: true);
        Assert.IsTrue(root.IsLoading); // backend query in flight

        // Further requests (double-click, keyboard) while loading must be ignored.
        treeTableView.RequestExpandCollapse(root, 0, expand: true);
        treeTableView.RequestExpandCollapse(root, 0, expand: false);
        Assert.AreEqual(1, expandRequests);
        Assert.AreEqual(3, treeTableView.Items.Count); // nothing inserted yet

        await source.CompletePendingExpandAsync();

        Assert.IsFalse(root.IsLoading);
        Assert.IsTrue(root.IsExpanded);
        Assert.AreEqual(5, treeTableView.Items.Count);

        await UnloadAsync(treeTableView);
    }

    [UITestMethod]
    public async Task NoOpRequests_AreFiltered()
    {
        var (treeTableView, source) = await LoadAsync();
        var requests = 0;
        treeTableView.ExpandRequested += (_, _) => requests++;
        treeTableView.CollapseRequested += (_, _) => requests++;

        treeTableView.RequestExpandCollapse(source[2], 2, expand: true);  // leaf: no children
        treeTableView.RequestExpandCollapse(source[0], 0, expand: false); // already collapsed

        Assert.AreEqual(0, requests);

        await UnloadAsync(treeTableView);
    }

    [UITestMethod]
    public async Task ChevronClick_RaisesExpandRequested_WithItemAndIndex()
    {
        var (treeTableView, source) = await LoadAsync();

        object? requestedItem = null;
        var requestedIndex = -1;
        treeTableView.ExpandRequested += (_, e) =>
        {
            requestedItem = e.Item;
            requestedIndex = e.Index;
        };

        // Dig out the chevron button generated by TableViewTreeColumn in row 1's first cell and invoke it.
        var row = (TableViewRow)treeTableView.ContainerFromIndex(1)!;
        var cellContent = (Grid)row.Cells[0].Content;
        var chevron = cellContent.Children.OfType<Button>().Single();
        ((ButtonAutomationPeer)FrameworkElementAutomationPeer.CreatePeerForElement(chevron)).Invoke();
        await Task.Yield();

        Assert.AreSame(source[1], requestedItem);
        Assert.AreEqual(1, requestedIndex);

        await UnloadAsync(treeTableView);
    }

    [UITestMethod]
    public async Task ObservableVectorSource_DirectMode_ExpandInsertsChildren()
    {
        // The app's target shape: a native IObservableVector<object> source (no INotifyCollectionChanged at all),
        // bound directly with UseCollectionView=false. VectorChanged must drive both the platform's rows and the
        // library's row-index invalidation.
        var source = new ObservableVectorTreeSource
        {
            new TreeNode { Name = "Root0", Depth = 0, ChildCount = 2 },
            new TreeNode { Name = "Root1", Depth = 0, ChildCount = 0 },
        };

        var treeTableView = new TreeTableView
        {
            AutoGenerateColumns = false,
            UseCollectionView = false,
            Width = 600,
            Height = 400,
        };
        treeTableView.Columns.Add(new TableViewTreeColumn
        {
            Header = "Name",
            Width = new GridLength(250, GridUnitType.Pixel),
            Binding = new Binding { Path = new PropertyPath(nameof(TreeNode.Name)) },
        });

        treeTableView.ExpandRequested += (_, e) =>
        {
            var node = (TreeNode)e.Item;
            var insertAt = source.IndexOf(node) + 1;
            for (var i = 0; i < node.ChildCount; i++)
            {
                source.Insert(insertAt + i, new TreeNode { Name = $"{node.Name}/Child{i}", Depth = node.Depth + 1 });
            }
            node.IsExpanded = true;
        };

        treeTableView.ItemsSource = source;
        await UnitTestApp.Current.MainWindow.LoadTestContentAsync(treeTableView);
        treeTableView.UpdateLayout();

        Assert.AreEqual(2, treeTableView.Items.Count);

        treeTableView.RequestExpandCollapse((TreeNode)source[0], 0, expand: true);
        await Task.Yield();
        treeTableView.UpdateLayout();

        Assert.AreEqual(4, treeTableView.Items.Count);
        Assert.AreEqual("Root0/Child0", ((TreeNode)treeTableView.Items[1]!).Name);

        var childRow = (TableViewRow)treeTableView.ContainerFromIndex(1)!;
        Assert.IsNotNull(childRow);
        Assert.AreSame(source[1], childRow.Content);

        await UnloadAsync(treeTableView);
    }

    [UITestMethod]
    public async Task DoubleClickPath_TreeCell_TogglesExpansion_LeavesFallThroughToEditing()
    {
        var (treeTableView, source) = await LoadAsync();
        var expandRequests = 0;
        treeTableView.ExpandRequested += (_, _) => expandRequests++;

        // Expandable root: the double-click path consumes the gesture and requests an expand.
        var rootRow = (TableViewRow)treeTableView.ContainerFromIndex(0)!;
        Assert.IsTrue(treeTableView.ToggleExpandCollapseFromCell(rootRow.Cells[0]));
        Assert.AreEqual(1, expandRequests);

        await source.CompletePendingExpandAsync();
        treeTableView.UpdateLayout();

        // Leaf child: not consumed — the caller falls through to normal cell editing.
        var leafRow = (TableViewRow)treeTableView.ContainerFromIndex(1)!;
        Assert.IsFalse(treeTableView.ToggleExpandCollapseFromCell(leafRow.Cells[0]));

        await UnloadAsync(treeTableView);
    }

    [UITestMethod]
    public async Task FinalItem_NeverRaisesExpandOrCollapse_OnAnyPath()
    {
        var (treeTableView, _) = await LoadAsync();
        var requests = 0;
        treeTableView.ExpandRequested += (_, _) => requests++;
        treeTableView.CollapseRequested += (_, _) => requests++;

        // Contradictory state on purpose: claims children AND finality — IsFinalItem must win on every path.
        var finalItem = new TreeNode { Name = "Final", Depth = 0, ChildCount = 5, IsFinalItem = true };

        treeTableView.RequestExpandCollapse(finalItem, 0, expand: true);
        treeTableView.RequestExpandCollapse(finalItem, expand: true);
        treeTableView.RequestExpandCollapse(finalItem, 0, expand: false);

        Assert.AreEqual(0, requests);

        // The double-click path does not consume the gesture either (falls through to editing).
        var row = (TableViewRow)treeTableView.ContainerFromIndex(0)!;
        row.Content = finalItem;
        Assert.IsFalse(treeTableView.ToggleExpandCollapseFromCell(row.Cells[0]));
        Assert.AreEqual(0, requests);

        await UnloadAsync(treeTableView);
    }

    [UITestMethod]
    public async Task RequestExpandCollapse_IndexFreeOverload_ResolvesIndex()
    {
        var (treeTableView, source) = await LoadAsync();

        var requestedIndex = -1;
        treeTableView.ExpandRequested += (_, e) => requestedIndex = e.Index;

        treeTableView.RequestExpandCollapse(source[1], expand: true); // Root1, flat index 1

        Assert.AreEqual(1, requestedIndex);

        await UnloadAsync(treeTableView);
    }

    [UITestMethod]
    public async Task IndentWidthChange_ReindentsRealizedCellsImmediately()
    {
        var (treeTableView, source) = await LoadAsync();
        var treeColumn = (TableViewTreeColumn)treeTableView.Columns[0];

        treeTableView.RequestExpandCollapse(source[0], 0, expand: true);
        await source.CompletePendingExpandAsync();
        treeTableView.UpdateLayout();

        var childRow = (TableViewRow)treeTableView.ContainerFromIndex(1)!; // depth 1
        var indent = (Microsoft.UI.Xaml.Controls.Border)((Grid)childRow.Cells[0].Content).Children[0];

        Assert.AreEqual(16d, indent.Width); // default IndentWidth x depth 1

        treeColumn.IndentWidth = 40;

        Assert.AreEqual(40d, indent.Width); // realized cell re-indented immediately, no rebind needed

        await UnloadAsync(treeTableView);
    }

    [UITestMethod]
    public async Task AutomationPeer_TreeRow_ReportsLevelAndDrivesExpandCollapse()
    {
        var (treeTableView, source) = await LoadAsync();

        var rootRow = (TableViewRow)treeTableView.ContainerFromIndex(0)!;
        var rootPeer = FrameworkElementAutomationPeer.CreatePeerForElement(rootRow);
        var provider = (Microsoft.UI.Xaml.Automation.Provider.IExpandCollapseProvider)
            rootPeer.GetPattern(PatternInterface.ExpandCollapse)!;

        Assert.AreEqual(1, rootPeer.GetLevel()); // depth 0 -> UIA level 1
        Assert.AreEqual(ExpandCollapseState.Collapsed, provider.ExpandCollapseState);

        provider.Expand(); // routes through TreeTableView.RequestExpandCollapse -> ExpandRequested
        Assert.AreEqual(ExpandCollapseState.PartiallyExpanded, provider.ExpandCollapseState); // async load in flight
        await source.CompletePendingExpandAsync();

        Assert.AreEqual(ExpandCollapseState.Expanded, provider.ExpandCollapseState);
        treeTableView.UpdateLayout();

        var childRow = (TableViewRow)treeTableView.ContainerFromIndex(1)!;
        var childPeer = FrameworkElementAutomationPeer.CreatePeerForElement(childRow);

        Assert.AreEqual(2, childPeer.GetLevel()); // depth 1 -> UIA level 2
        Assert.AreEqual(ExpandCollapseState.LeafNode,
            ((Microsoft.UI.Xaml.Automation.Provider.IExpandCollapseProvider)
                childPeer.GetPattern(PatternInterface.ExpandCollapse)!).ExpandCollapseState);

        await UnloadAsync(treeTableView);
    }

    private static async Task<(TreeTableView TreeTableView, FlatTreeSource Source)> LoadAsync()
    {
        // 3 roots; roots 0 and 1 report 2 unrealized children each (count known, items not loaded), root 2 is a leaf.
        var source = new FlatTreeSource
        {
            new TreeNode { Name = "Root0", Depth = 0, ChildCount = 2 },
            new TreeNode { Name = "Root1", Depth = 0, ChildCount = 2 },
            new TreeNode { Name = "Root2", Depth = 0, ChildCount = 0 },
        };

        var treeTableView = new TreeTableView
        {
            AutoGenerateColumns = false,
            SelectionMode = ListViewSelectionMode.Extended,
            Width = 600,
            Height = 400,
        };

        treeTableView.Columns.Add(new TableViewTreeColumn
        {
            Header = "Name",
            Width = new GridLength(250, GridUnitType.Pixel),
            Binding = new Binding { Path = new PropertyPath(nameof(TreeNode.Name)) },
        });
        treeTableView.Columns.Add(new TableViewTextColumn
        {
            Header = "Depth",
            Binding = new Binding { Path = new PropertyPath(nameof(TreeNode.Depth)) },
        });

        treeTableView.ExpandRequested += (_, e) => source.BeginExpand((TreeNode)e.Item);
        treeTableView.CollapseRequested += (_, e) => source.Collapse((TreeNode)e.Item);
        treeTableView.ItemsSource = source;

        await UnitTestApp.Current.MainWindow.LoadTestContentAsync(treeTableView);
        treeTableView.UpdateLayout();

        return (treeTableView, source);
    }

    private static async Task UnloadAsync(TreeTableView treeTableView)
        => await UnitTestApp.Current.MainWindow.UnloadTestContentAsync(treeTableView);

    /// <summary>
    /// Reference flat tree source matching the app's backend model: a node's child COUNT is known upfront
    /// (HasChildren), the children themselves are fetched asynchronously on expand. Children are inserted right
    /// after the parent, located BY REFERENCE (the request index may be stale by the time the query completes).
    /// </summary>
    private sealed class FlatTreeSource : ObservableCollection<TreeNode>
    {
        private TaskCompletionSource? _pendingExpand;
        private TreeNode? _pendingNode;

        public void BeginExpand(TreeNode node)
        {
            node.IsLoading = true; // "backend query" starts
            _pendingNode = node;
            _pendingExpand = new TaskCompletionSource();
        }

        /// <summary>Simulates the backend responding with the children.</summary>
        public async Task CompletePendingExpandAsync()
        {
            var node = _pendingNode!;
            var insertAt = IndexOf(node) + 1; // locate by reference, not by the request-time index

            for (var i = 0; i < node.ChildCount; i++)
            {
                Insert(insertAt + i, new TreeNode
                {
                    Name = $"{node.Name}/Child{i}",
                    Depth = node.Depth + 1,
                    ChildCount = 0,
                });
            }

            node.IsExpanded = true;
            node.IsLoading = false;
            _pendingExpand!.SetResult();
            _pendingExpand = null;
            _pendingNode = null;

            await Task.Yield(); // let bindings/layout react
        }

        public void Collapse(TreeNode node)
        {
            var index = IndexOf(node);

            // Remove the contiguous run of deeper items following the node (its visible descendants).
            while (index + 1 < Count && this[index + 1].Depth > node.Depth)
            {
                RemoveAt(index + 1);
            }

            node.IsExpanded = false;
        }
    }

    /// <summary>
    /// Minimal native-notification source: implements <see cref="IObservableVector{T}"/> of object (what the XAML
    /// platform consumes directly, no INotifyCollectionChanged conversion) over a plain list. Reference shape for
    /// an app collection that prefers VectorChanged.
    /// </summary>
    private sealed class ObservableVectorTreeSource : IObservableVector<object>
    {
        private readonly List<object> _items = [];

        public event VectorChangedEventHandler<object>? VectorChanged;

        public object this[int index]
        {
            get => _items[index];
            set
            {
                _items[index] = value;
                VectorChanged?.Invoke(this, new VectorChangedArgs(CollectionChange.ItemChanged, (uint)index));
            }
        }

        public int Count => _items.Count;
        public bool IsReadOnly => false;

        public void Add(object item) => Insert(_items.Count, item);

        public void Insert(int index, object item)
        {
            _items.Insert(index, item);
            VectorChanged?.Invoke(this, new VectorChangedArgs(CollectionChange.ItemInserted, (uint)index));
        }

        public void RemoveAt(int index)
        {
            _items.RemoveAt(index);
            VectorChanged?.Invoke(this, new VectorChangedArgs(CollectionChange.ItemRemoved, (uint)index));
        }

        public bool Remove(object item)
        {
            var index = _items.IndexOf(item);
            if (index < 0) return false;
            RemoveAt(index);
            return true;
        }

        public void Clear()
        {
            _items.Clear();
            VectorChanged?.Invoke(this, new VectorChangedArgs(CollectionChange.Reset, 0));
        }

        public bool Contains(object item) => _items.Contains(item);
        public void CopyTo(object[] array, int arrayIndex) => _items.CopyTo(array, arrayIndex);
        public int IndexOf(object item) => _items.IndexOf(item);
        public System.Collections.Generic.IEnumerator<object> GetEnumerator() => _items.GetEnumerator();
        System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator() => _items.GetEnumerator();

        private sealed class VectorChangedArgs(CollectionChange change, uint index) : IVectorChangedEventArgs
        {
            public CollectionChange CollectionChange => change;
            public uint Index => index;
        }
    }

    private sealed class TreeNode : ITableViewTreeItem, INotifyPropertyChanged
    {
        private bool _isExpanded;
        private bool _isLoading;

        public event PropertyChangedEventHandler? PropertyChanged;

        public string Name { get; init; } = string.Empty;
        public int Depth { get; init; }
        public int ChildCount { get; init; }

        public bool HasChildren => ChildCount > 0;
        public bool IsFinalItem { get; init; }
        public System.Collections.Generic.IEnumerable<ITableViewTreeItem>? ChildrenSource => null; // flat-source model

        public bool IsExpanded
        {
            get => _isExpanded;
            set => Set(ref _isExpanded, value, nameof(IsExpanded));
        }

        public bool IsLoading
        {
            get => _isLoading;
            set => Set(ref _isLoading, value, nameof(IsLoading));
        }

        private void Set(ref bool field, bool value, string name)
        {
            if (field != value)
            {
                field = value;
                PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(name));
            }
        }
    }
}
