<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
		<TargetPlatformMinVersion>10.0.19041.0</TargetPlatformMinVersion>
		<WindowsSdkPackageVersion>10.0.26100.84</WindowsSdkPackageVersion>
		<Platforms>x64</Platforms>
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
		<UseWinUI>true</UseWinUI>
		<SatelliteResourceLanguages>en</SatelliteResourceLanguages>
		<RestoreConfigFile></RestoreConfigFile>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<LangVersion>14</LangVersion>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<IsAOTCompatible>true</IsAOTCompatible>
	</PropertyGroup>
  <PropertyGroup Condition="!$(Configurations.Contains('$(Configuration)')) And '$(Configuration)' != ''">
    <!-- This appends the active build configuration to the recognized list -->
    <Configurations>$(Configurations);$(Configuration)</Configurations>
  </PropertyGroup>
	<ItemGroup>
		<Compile Update="TableView.*.cs">
			<DependentUpon>TableView.cs</DependentUpon>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="WinUI.TableView.Tests" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Windows.SDK.BuildTools" />
		<PackageReference Include="Microsoft.WindowsAppSDK" />
	</ItemGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <PackageId>Luxonit.WinUI.TableView</PackageId>
    <DebugType>portable</DebugType>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <AllowedOutputExtensionsInPackageBuildOutputFolder>.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <GenerateLibraryLayout>true</GenerateLibraryLayout>
    <Description>TableView/DataGrid control for WinUI.</Description>
    <PackageTags>WinUI, WinAppSDK, Windows, UNO, XAML, TableView, DataGrid</PackageTags>
    <Product>WinUI TableView Control</Product>
    <RepositoryUrl>https://github.com/w-ahmad/WinUI.TableView</RepositoryUrl>
    <PackageProjectUrl>https://w-ahmad.github.io/WinUI.TableView/</PackageProjectUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageIcon>icon.png</PackageIcon>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageOutputPath>$(MSBuildThisFileDirectory)..\artifacts\NuGet\$(Configuration)\</PackageOutputPath>
    <Authors>w-ahmad - https://github.com/w-ahmad</Authors>
  </PropertyGroup>

  <ItemGroup Condition="'$(Configuration)' == 'Release'">
    <PackageReference Include="Microsoft.SourceLink.GitHub">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <None Include="..\README.md" Pack="true" PackagePath="\" />
    <None Include="..\package-icon.png" Pack="true" PackagePath="\icon.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="PolySharp" />
  </ItemGroup>

</Project>
